### ISSUE TITLE
Windows binaries 32/64 bit of Horus Chess

### ISSUE THREAD

**Issue by ChessGUI** [universecoder/Horus-Chess-Engine#1]
Hello universecoder,

can you please build Windows binaries 32/64 bit for Horus Chess and host these files on your website, too?

**Comment by pranav-deshpande** [comment]
Hello,
Sorry for the late reply. I am planning to do what you say. As of now, I'm a bit busy due to my university examinations. I'll resume the work after that(about 22 days more to go).

Regards,
Pranav.

**Comment by ChessGUI** [comment]
Hello Pranav,

32/64 bit Windows executable files are here available: 
http://www.andscacs.com/horus/horus.zip
   Engine               Score            Ho           Di           Hi           Tu    S-B
1: Horus32              22,5/36 ············ ============ 10111=====1= 111=11011==0  368,25
2: Dikabi               17,5/36 ============ ············ 010=0=0=0=0= 111====1==01  312,25
3: Hippocampe v0.4.1 DC 17,5/36 01000=====0= 101=1=1=1=1= ············ =1======000=  311,25
4: TuxedoCat32          14,5/36 000=00100==1 000====0==10 =0======111= ············  271,25

72 games played / Tournament is finished
Name of the tournament: 21-12-2016.at
Site/ Country: I5COREQUAD, Germany
Level: Tournament 40/2
Hardware: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz with 3,2 GB Memory
Operating system: Windows 7 Home Premium Home Edition Service Pack 1 (Build 7601) 32 bit   

 Another x64 Horus compile :
[Horus-Chess-Engine-master.zip](https://github.com/universecoder/Horus-Chess-Engine/files/673756/Horus-Chess-Engine-master.zip)


![horus chess 1](https://cloud.githubusercontent.com/assets/2707025/21494880/b77884a0-cc14-11e6-9ce9-0e5d9124a192.jpg)
![horus chess 2](https://cloud.githubusercontent.com/assets/2707025/21494885/c0f6caaa-cc14-11e6-8288-66c4488028ca.jpg)
![horus chess 3](https://cloud.githubusercontent.com/assets/2707025/21494889/c8afb090-cc14-11e6-9849-cf09c83f97eb.jpg)
![horus chess 4](https://cloud.githubusercontent.com/assets/2707025/21494897/d2c5ba98-cc14-11e6-9a68-a6539c34c945.jpg)
![horus chess 5](https://cloud.githubusercontent.com/assets/2707025/21494905/d9a050f8-cc14-11e6-9d3f-79ae03f4f4d6.jpg)
![horus chess 6](https://cloud.githubusercontent.com/assets/2707025/21494914/df762174-cc14-11e6-8576-67c6f6d807a6.jpg)

You can use these logos with several graphical interfaces: Arena, ChessGUI, WinBoard etc. - just rename the ending .jpg into .bmp (bitmap) with Ant Renamer http://www.antp.be/software/renamer or PhotoFiltre http://photofiltre.free.fr/
cf. CCRL list http://www.computerchess.org.uk/ccrl/404/

**Comment by pranav-deshpande** [comment]
Thank you for your help! The issue was out of my mind. I will begin adding more stuff to Horus soon. Why did you send me the CCRL list though? Also, what is this tournament you are talking about?

**Comment by ChessGUI** [comment]
The target of CCRL 40/4 list is to compare the rating of Horus with the playing strength of other engines.
(time control: 40 moves/4 minutes). I am not a member of this group, but perhaps you could join their forum http://kirill-kryukov.com/chess/discussion-board/ (if you are interested in).

**Comment by yellow-panther** [comment]
By the way: Could you add Windows binaries of you recent source code now (without the option bmi2)?
Daniel José www.andscacs.com made former Windows binaries, not I!
I edited only the Horus logos.
https://en.wikipedia.org/wiki/Bit_Manipulation_Instruction_Sets
